version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './apps/my-symfony-app/:/usr/src/app'
    user: ${LOCAL_USER}

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/my-symfony-app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '${ADMINER_PORT}:8080'
